name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image
      run: |
        docker build -t itsnaeemraza/server:${{ github.sha }} ./server
        docker push itsnaeemraza/server:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
    - name: Executing remote SSH commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu
          git pull
          IMAGE_TAG=${{ github.sha }} sed -i 's|image: itsnaeemraza/server:.*|image: itsnaeemraza/server:'"$IMAGE_TAG"'|' docker-compose.yml
          docker-compose up -d

    - name: Send notification to Gmail
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: Deployment Status
        body: Deployment of ${{ github.repository }} was successful. Commit SHA: ${{ github.sha }}
        to: itsnaeemraza@gmail.com
        from: GitHub Actions <id.naeemraza@gmail.com>
        secure: true
